language: python
python:
    - "3.5"

os:
    - linux
dist: xenial

sudo: true

install:
  - sudo echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install r-base r-base-dev
  - pip install --upgrade pip
  - python setup.py install
  - pip install pytest-cov
  - pip install coveralls 

script:
    - py.test 
    
after_success:
    - coveralls

