language: python
python:
    - "3.5"

os:
    - linux
dist: xenial

sudo: true

install:
  - sudo add-apt-repository https://cran.rstudio.com/bin/linux/ubuntu
  - sudo apt-get update
  - sudo apt-get install r-base-dev
  - pip install --upgrade pip
  - python setup.py install
  - pip install pytest-cov
  - pip install coveralls 
